const data = [
    {
        title: "The Claytons",
        location: "Knoxville, TN",
        rating: 4.6,
        udiscUrl: "https://udisc.com/courses/the-claytons-W7lp",
        date: "06/21/22",
        description: "Championship Level Course. Permanent dual baskets on every hole with holes 1, 15 & 18 having short and long tees as well as baskets. The course is always in great condition. Tee pads are Concrete with most having turf. ",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/d5defe0e21ddf7738b34895fe6ac2d6a_m_IMG_1317.jpg",
    },
    {
        title: "Eagles Crossing",
        location: "Hawk Point, MO",
        rating: 4.9,
        udiscUrl: "https://udisc.com/courses/eagles-crossing-JQQP",
        date: "06/23/22",
        description: "Eagles Crossing is a premier, world-class disc golf course and outdoor recreation facility, nestled on 400 acres of serene rolling hills near the small town of Hawk Point, Missouri. Eagles Crossing is a par-70, 18-hole disc golf course that offers the very best in challenging, championship-level disc golf play. The course was designed by PDGA hall of famer, David McCormack, and is considered to be among the best disc golf courses in the world.",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/c75b2b2d77ae48cca71d0421deef67dc_m_IMG_7095.jpg",
    },
    {
        title: "Jones Park - Supreme",
        location: "Emporia, KS",
        rating: 4.5,
        udiscUrl: "https://udisc.com/courses/jones-park-supreme-i41h",
        date: "06/24/22",
        description: "This is the new championship level course at Jones Park. This course replaces the previous Jones West, Jones East, and Jones Gold courses. Both courses are a current work in progress with tee signs. All layouts are currently active.",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/f03ea4b1054902d689a4937491ebf7b6_m_D40B7AA2_D3E4_468E_973B_D4C4A925B7F1.jpg",
    },
    {
        title: "Solitude Mountain Resort",
        location: "Brighton, UT",
        rating: 4.7,
        udiscUrl: "https://udisc.com/courses/solitude-mountain-resort-ZeA7",
        date: "06/26/22",
        description: "Starting at 9,000 feet, Solitude's 18-hole course is one of Utah's finest high-altitude courses.",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/c126f209d8e6672c67d27f8d50cb237a_m_4io0s9JMWsLfjBiVqoCZZ4z3T3JW.jpg",
    },
    {
        title: "Skyline Wilderness Park",
        location: "Napa, CA",
        rating: 4.4,
        udiscUrl: "https://udisc.com/courses/skyline-wilderness-park-upper-course-I3Qt",
        date: "07/02/22",
        description: "Challenging course set in the hills of Napa Valley. Two baskets are in for on each tee pad at all times. Layout changes frequently. Bring water.",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/19c1efa00b5fa190f3a4786464fffeb2_m_IMG_2644.jpg",
    },
    {
        title: "Rosa Park",
        location: "Santa Rosa, CA",
        rating: "4.0",
        udiscUrl: "https://udisc.com/courses/rosa-park-4zEH",
        date: "07/03/22",
        description: "This is a technical course that will really challenge you. Most baskets are surrounded by low hanging trees so it's all about accuracy.",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/92ae311d0d57c8791634411188d13926_m_oCu3vOlMIVTtRmtR8PUK8LiDzjRe.jpg",
    },
    {
        title: "Taylor Mountain",
        location: "Santa Rosa, CA",
        rating: 4.3,
        udiscUrl: "https://udisc.com/courses/taylor-mountain-7zMP",
        date: "07/07/22",
        description: "Hilly, grassy, rocky, woodsy. Lots of technical shots up or down hills with a few longer holes mixed in.",
        imageUrl: "https://d22ksth68ujgu2.cloudfront.net/d51113240c2c5ff52cf11ebdf4e5260c_m_YdUkgbpQB4v2i5HmXZOw3L3Fpw76.jpg",
    },
]

export default data